### ISSUE TITLE
Please add tags to create a release for MELPA Stable

### ISSUE THREAD

**Issue by Trevoke** [ananthakumaran/typescript.el#21]
MELPA Stable finds tags in repos (such as 0.5.74) and uses those to create stable releases. For those of us who prefer to depend on stable code, this is a godsend. Please create a git tag for code you consider stable, thanks :)

**Comment by josteink** [comment]
I've pushed a [v0.1 tag](https://github.com/ananthakumaran/typescript.el/tree/v0.1) for now, so that at least *something* shows up on MELPA Stable.

How often subsequent releases will be pushed, and how much changes to expect, I have no idea about, and can't make any promises.
