### ISSUE TITLE
Please add a copy of GPLv3 to the repo

### ISSUE THREAD

**Issue by rwhogg** [ananthakumaran/typescript.el#26]
The ELisp file says we should have received a copy of it.

Thanks! :smile_cat:

**Comment by josteink** [comment]
Boring licensing is boring licensing but I guess you're absolutely technically correct. 

 I'll look into it this evening.

**Comment by rwhogg** [comment]
> Boring licensing is boring licensing

Yeah, I know. Sorry, I hope dealing with this isn't terribly annoying.

**Comment by josteink** [comment]
No worries. Right should be right. Thanks for helping us stay fully compliant :)
