### ISSUE TITLE
'typescript-insert-and-indent' is weird when the line contains Chinese

### ISSUE THREAD

**Issue by xzedx** [ananthakumaran/typescript.el#33]
![typsecript-issue](https://cloud.githubusercontent.com/assets/6986864/24575153/94e085bc-16d0-11e7-9f07-a909541c98d5.gif)

**Comment by josteink** [comment]
Thanks for the bug report. Double-width characters are known to cause problems in naive code...

I'll see if I can't investigate this later on.

**Comment by josteink** [comment]
I've tested with the following simple code:

````typescript
class Testy {
    test() {
        let x = "大塚 愛";
    }
}
````

Upon pressing `;` at the end there, I do get weird behaviour.

For a scenario similar to yours I get more behaviour like this:

````typescript
class Testy {
    test() {
        test("大塚 愛", function()
    }
}
````

Upon typing the opening paren in `function()`, the cursor gets moved thee characters ahead of where it should be.

**Basically: After three wide characters the cursor is now three points ahead of where it should actually be! I refuse to believe that is a coincidence.**

What seems to trigger is this section here: https://github.com/ananthakumaran/typescript.el/blob/master/typescript-mode.el#L484-L485

````elisp
(and (not (nth 8 syntax))
      typescript-auto-indent-flag)
````

I'll be honest and say I have no idea what that's supposed to mean, but when this code reports `t` back, what gets run is `indent-according-to-mode`, and that's what's triggering this behaviour. Could this be an error in `indent.el`?

Running `indent-according-to-mode` manually on any portion of the code with these wide characters does seem to lead to weird things, with the cursor-position often being calculated incorrectly.

For a quick workaround, I suggest you just set the `typescript-auto-indent-flag` defcustom to `nil`. This will suppresses this behaviour (and conceals the bug).

In the meantime, I'm not sure if this is a bug in our mode or if there are unicode errors in core Emacs functions. I'll try to get some help in these matters.

**Comment by josteink** [comment]
I've found the culprit. [It's our code](https://github.com/ananthakumaran/typescript.el/blob/master/typescript-mode.el#L1798-L1807).

````elisp
(defun typescript-indent-line ()
  "Indent the current line as typescript."
  (interactive)
  (save-restriction
    (widen)
    (let* ((parse-status
            (save-excursion (syntax-ppss (point-at-bol))))
           (offset (- (current-column) (current-indentation))))
      (indent-line-to (typescript--proper-indentation parse-status))
(when (> offset 0) (forward-char offset)))))
````

We're doing some weird calculations here, and that results in a "offset" between the original and the indented version, and a attempt to fix this mismatch.

Clearly we're calculating some things wrong here.

**Comment by Kethku** [comment]
I just started running into this when I switched to using fira code with the symbols font for pseudo ligatures. Any idea if this will get fixed?

**Comment by josteink** [comment]
> Any idea if this will get fixed?

I must admit I don't really understand the code inside `typescript--proper-indentation`, so getting this fixed will take a bit more effort than a "normal" bug-fix.

Right now I don't have much spare time for such concentrated efforts, and given how it doesn't affect me directly, I also lack the motivation for diving into it, in the few cases where I do have spare-time.

If anyone else feels like taking a stab at this, I'll be happy to review any incoming patches though.

**Comment by josteink** [comment]
**Update:** I hate to leave code to rot, so I decided to a minimal effort debugging.

I used the following test-buffer:

````typescript
export class Moo {
    let x = "abc";
    let y = "大塚愛";
}
````

Pressing `;` after the line with `"abc"` resulted in `typescript--proper-indentation` returning `4` (which is correct).

Pressing `;` after the line with `"大塚愛"` also resulted in `typescript--proper-indentation` returning `4` (which again is the correct value).

So clearly the error is in the offset-calculation in [`typescript-indent-line`](https://github.com/ananthakumaran/typescript.el/blob/master/typescript-mode.el#L1798-L1807) where we try to regain our original position after re-indenting the line. That should be much more manageable to analyse and debug, even for non-Elisp experts.

**Comment by josteink** [comment]
Nailed it: The problem is `current-column` counts wide-chars as several characters, causing a API impedance-mismatch with `forward-char` (which doesn't).

This is easy to demonstrate. Take the following line in any mode:

````
abcd大塚愛
````

Put the cursor after the `d`, and eval `(prin1 (current-column))`. It should print `4`.

Now put the cursor after the `大`, and eval `(prin1 (current-column))`. Our algorithm expects it to return `5`, but it returns `6`.

Are there any options to `current-column` which correctly accounts for wide characters?

**Comment by josteink** [comment]
I've added a new function `typescript-current-column` which is unicode-aware and employed that instead in `typescript-indent-line`.

As far as I can see, this fixes this issue.

I also observe that we use `current-column` lots of other places in our code, but until someone can demonstrate that this is causing issues elsewhere, in the name of cautiousness I've left those as is.

If we have issues they should then be trivial to migrate to `typescript-current-column`.
