### ISSUE TITLE
font highlighter ends regexp prematurely

### ISSUE THREAD

**Issue by lddubeau** [ananthakumaran/typescript.el#44]
Given the following regexp:

```
/[a/b]/
```

The regexp will be highlighted as a regexp from the first forward slash, until the 2nd forward slash. However, the regexp really ends at the last forward slash. (For the benefit of readers who may not know: a forward slash appearing in `[...]` is treated as *part of* the regexp instead of treated as *terminating* the regexp. The regex above matches the characters `a`, `/` and `b`.)

I guess it is the twin of #34.

This issue does not annoy me enough to get to work on a solution in the short term so anyone is welcome to fix it and reap the glory. :)

**Comment by josteink** [comment]
I've tested and this also seems fixed in PR #45.

**Comment by josteink** [comment]
With PR 45 closed and not merged, I guess we will need to seek an alternate solution to this issue.

**Comment by nnabinh** [comment]
Up, pls fix this

**Comment by josteink** [comment]
PRs are welcome :)
