### ISSUE TITLE
Add support for highlighting typedoc/jsdoc comments

### ISSUE THREAD

**Issue by lddubeau** [ananthakumaran/typescript.el#49]
Having proper highlighting of typedoc/jsdoc comments, besides providing visual help, would allow skipping things that don't need spell-checking when using `flyspell-prog-mode`.

For instance, in the following:

```
/**
 * @param {SomeType} blah something
 */
```

The only thing that needs spell checking is "something". The rest is either a typedoc/jsdoc tag (`@param`), a type reference (`SomeType`) or a parameter name (`blah`). Flyspell determines whether a piece of text should be spell-checked by seeing whether it has any of the faces in `flyspell-prog-text-faces`. Right now `typescript-mode` assigns `font-lock-comment-face` to the whole comment and thus everything is subject to spell checking.

As usual, `js-mode` has no support for this, whereas `js2-mode` distinguishes the various parts appropriately.

**Comment by josteink** [comment]
I support the idea, but I don't have time to implement this right now.

In my email to emacs-devel for issue https://github.com/ananthakumaran/typescript.el/issues/48, I've also mentioned the ability to escape not only strings but also comments... 

So maybe we'll in time see some more fundamental building blocks to handle syntax like this.

In the meantime, I guess the simplest way to land this for now (in a cross-version compatible way) would be simple font-lock regexes.

What that won't solve though (iirc) is the *syntax-properties* of the highlighted text, so `flyspell-prog-mode` is probably still going to be noisy about these statements.

**Comment by lddubeau** [comment]
> What that won't solve though (iirc) is the *syntax-properties* of the highlighted text, so `flyspell-prog-mode` is probably still going to be noisy about these statements.

Flyspell cares only about the faces used, not the syntax properties.

I've pushed an experiment to https://github.com/ananthakumaran/typescript.el/tree/experiment/typedoc-tags

It works but is still incomplete. The regular expressions were taken from `js2-mode` and the variable/face names were derived from those there.

Things that are missing to reduce the number of false misspelling errors reported by Flyspell, besides fleshing out the jsdoc/typedoc support:

1. The strings in `import` statements should not be spell checked. To support this though I'm thinking `typescript-mode` should acquire a custom predicate that Flyspell can use to know whether a word should be checked or not. I had forgotten this feature, but setting the property `flyspell-mode-predicate` on the mode's name overrides the default predicate that `flyspell` uses.

2. ``tslint`` flags should also be excluded from spell checking. I'm thinking it would be nice to also have them be fontified with a different face than `font-lock-comment-face` so that besides being excluded from spell checking, they stand out from random comments.

**Comment by josteink** [comment]
List to the relevant emacs-devel thread for those interested:

https://lists.gnu.org/archive/html/emacs-devel/2017-08/msg00560.html

**Comment by lddubeau** [comment]
Fixed by https://github.com/ananthakumaran/typescript.el/commit/782e8dd32e7b30fbecd52ff49eaa65b78af0800f and https://github.com/ananthakumaran/typescript.el/commit/7172a23d86d7b40c1b850429d805f3a39bdf3baa
