### ISSUE TITLE
Do we need the fontification hack?

### ISSUE THREAD

**Issue by lddubeau** [ananthakumaran/typescript.el#50]
The mode initialization code contains this [hack](https://github.com/ananthakumaran/typescript.el/blob/813cf4fef30d95d055268c06afaf61b4b4f49878/typescript-mode.el#L2264-L2268):

```
  (let (font-lock-keywords)         ; leaves syntactic keywords intact
    ;; Avoid byte-compilation errors.  `font-lock-fontify-buffer' is
    ;; marked as interactive only in Emacs 25.
    (with-no-warnings
      (font-lock-fontify-buffer)))
```

The code above prevents users from having a `typescript-mode-hook` that immediately turns on `flyspell-prog-mode` and performs `flyspell-buffer` so that all spelling errors are immediately marked when `typescript-mode` starts. The problem with the code above is that it performs a fontification that only takes into account the syntactic classes of the text without applying the rules in `font-lock-keywords`. I've setup my flyspell predicate so that it requires the buffer to have been fontified at least up to the point it needs to examine. However, the first fontification triggered above does not contain the result of applying the rules in `font-lock-keywords`, which do matter for the predicate to work properly. So the initial `flyspell-buffer` run is running with incomplete fontification information, and ends up spell checking words that should not be spell-checked.

I worked around the problem by refontifying the buffer before starting `flyspell-prog-mode` and `flyspell-buffer`.

(Note: it would be *possible* to setup a predicate for flyspell that does not depend on fontification information. However, the predicate would get complicated *fast*. I'd rather avoid this if at all possible.)

I took a glance at `js-mode` and it looks like it *used* to perform an immediate fontification but that this immediate fontification was removed:

```
  ;; Important to fontify the whole buffer syntactically! If we don't,
  ;; then we might have regular expression literals that aren't marked
  ;; as strings, which will screw up parse-partial-sexp, scan-lists,
  ;; etc. and produce maddening "unbalanced parenthesis" errors.
  ;; When we attempt to find the error and scroll to the portion of
  ;; the buffer containing the problem, JIT-lock will apply the
  ;; correct syntax to the regular expression literal and the problem
  ;; will mysteriously disappear.
  ;; FIXME: We should instead do this fontification lazily by adding
  ;; calls to syntax-propertize wherever it's really needed.
  ;;(syntax-propertize (point-max))
```

So do we need that hack? I can run the test suite just fine without it (but that may not be saying much), and cannot point to a reason for the existence of the hack. I've removed it from my local copy of `typescript-mode` but I cannot tell whether removing it is actually causing issues because I do a full buffer fontification in my mode hook anyway to run the spell-checker.

**Comment by josteink** [comment]
Looking at `git blame` we can see this section is from the very first initial commit (or copy-paste if you like) of `typescript.el`.

That dates it at least years back, without any of the "active" maintainers actually being in any way involved with it.

Looking for the originating source for this mode (`javascript.el`), I had to go digging in [the Wayback machine](http://web.archive.org/web/20130313070358/http://www.karllandstrom.se/downloads/emacs/javascript.el)

Key finding: The latest snapshot there is from 2013, and does not contain this hack.

@ananthakumaran Care to help out here? Do you remember where you got this code from? Did you add it?

**Comment by ananthakumaran** [comment]
> Do you remember where you got this code from?
I don't remember the details :). I think I got it from a zip file somewhere.

> Did you add it?
Nope, definitely not.

**Comment by ananthakumaran** [comment]
@josteink Looks like this is copied from [tide](https://github.com/ananthakumaran/tide/commit/d557fa54a3237b11ba2459b028ddc636defba8fe) which is copied from [emacs-tss](https://github.com/aki2o/emacs-tss/commit/9592f5c53f2e5689f8639285f9474cf54746b419) which still contains the same hack.
