### ISSUE TITLE
commented lines are sometimes treated as non-comments

### ISSUE THREAD

**Issue by josteink** [ananthakumaran/typescript.el#57]
This causes errors with both font-lock and indentation.

This can be demonstated in the [indentation reference document](https://github.com/ananthakumaran/typescript.el/blob/30391a518a1d41d5c534a30850a50b0974132aec/test-files/indentation-reference-document.ts#L34-L35) where the following lines will be syntax-highlighted (and have syntax-properties) as if they were not commented:

````typescript
        //     case "linux":
        //     case "android": {
````

I can reproduce this on Emacs 25.3 (Fedora) and Emacs git master.

When trying to pinpoint where it goes wrong using `font-lock-studio` it seems none of the expressions picked up by `font-lock-studio` contributes to this error-condition, but instead it is immediately reproduced after exiting it (but then only the line with `"linux"` in it).

Could this be related to something we explicitly override in our mode outside the regular font-lock and syntax constructs, like `syntax-begin-function`?

**Edit:** Can also reproduce on Emacs 25.1 on Windows.

**Comment by oneeman** [comment]
I'm running into this too.  It always seems to involve a comment line after a comment line with a `:` in it.  The `:` doesn't have to be at the end of the line.

An odd thing I'm seeing is that often a comment line which is highlighted incorrectly will switch to being highlighted correctly if I make and and undo a change (e.g. add an extra space in the middle and then delete it).  For example, with your snippet, it gets highlighted incorrectly if I paste it into a buffer.  But if I then add and remove a space at the beginning of the second line, it's then correctly highlighted as a comment.

I haven't yet tried this on a clean emacs setup with just typescript mode.

**Comment by josteink** [comment]
Given that these issues do somehow *not* fail our indentation tests, while trying to replay those tests interactively visibly causes errors, backs up your observation that this clearly is affected by code meant to handle interactive changes.

I guess a first step would be to do a git bisect to see if we can find a point in time where this bug was not present. I'm fairly certain this behaviour has not always been like this.

**Comment by oneeman** [comment]
Agreed, something definitely broke that was working before.  I tried commit `30391a5` and it's fine for me, so the break seems to have been in `4b69ca5`.

Another example of broken highlighting which I'm seeing:

```
myFunction(
  "hello", // it's
)
```

The comment is not recognized as a comment, with the result that the `'` is interpreted as the beginning of a string, and everything after that is highlighted as if it were a string.  Unlike the examples above, this one seems to persist no matter what changes I do and undo.

**Comment by lddubeau** [comment]
Please try out the changes in #58.

I ran into the problem while editing a file and it was enough of a headache that I decided to work on it. This has been put together very quickly so maybe there's some case I've missed.

**Comment by oneeman** [comment]
Thanks.  I can't comment on whether it covers all the cases, but the change you made works fine for the cases I've noticed which were broken.

**Comment by josteink** [comment]
Awesome. Good work everyone!
