### ISSUE TITLE
Emacs frozen on TypeDoc

### ISSUE THREAD

**Issue by janesser** [ananthakumaran/typescript.el#65]
Hi,

i tried with http://typedoc.org/guides/doccomments/

whenever i type "/**" and then hit enter, emacs freezes and becomes unusable.
I've got to kill/restart it.

i can actually make that comment, but i must not push enter on that code-line.

Any hints?

**Comment by josteink** [comment]
I'm not able to to reproduce this issue at all.

Does it still fail on your end if you start on a clean config (`emacs -Q`) and install nothing but `tide`?

**Comment by janesser** [comment]
I'll try.

**Comment by janesser** [comment]
Tried to reproduce with tide only. Everything works fine.

Everything is now also fine with my normal installation, see here:
https://github.com/janesser/xmonad.hs/blob/master/.emacs

Appearently the problem has been solved in the meanwhile. If fix is known, please link here.

**Comment by josteink** [comment]
Glad you worked it out!
