### ISSUE TITLE
Errors no longer highlighted in compilation-mode

### ISSUE THREAD

**Issue by KevinVillela** [ananthakumaran/typescript.el#77]
Between TS 2.6 and 2.7 (so maybe around May 2018) they changed the format of the error messages, resulting in next-error not always working in compilation-mode.
I believe this needs to be updated: https://github.com/ananthakumaran/typescript.el/blob/a922c27e95948a13e6a72e2620ca592a744721a7/typescript-mode.el#L2529.

**Comment by josteink** [comment]
Looks fairly simple.

I’ll take a stab at it once I have time the next few days, unless of course anyone beats me to it.

**Comment by josteink** [comment]
Trying to reproduce (using latest typescript) I'm not able to reproduce:

![image](https://user-images.githubusercontent.com/411338/42202404-95630f6c-7e9b-11e8-86b2-18b9d203a770.png)

Could you show some example output from your compilation-mode buffer?

**Comment by KevinVillela** [comment]
Sure, sorry for the delay here, I was on holiday. I think I've figured it out, looks like the error regex doesn't like double-digit columns. Here's my .ts file:
`
  const a: string = 2;
   const a: string = 2;
`
path/to/app_component.ts:1:9 - error TS2451: Cannot redeclare block-scoped variable 'a'.

1   const a: string = 2;
          ~
path/to/app_component.ts:2:10 - error TS2451: Cannot redeclare block-scoped variable 'a'.

2    const a: string = 2;

The first one is highlighted, but the second one isn't. Seems like for whatever reason, my errors separate the line and column information with a colon, while yours use a comma.

**Comment by josteink** [comment]
Ok. So testing a little on my Linux machine, I see two major changes now...

1. Ansi colours in the output... Not sure how that's going to play with our regexps.
2.Which is a lot harder to notice because of the Ansi-colours... A new format for file & line!

The format of errors themselves does not seem to have changed though, and quotes or anything like that is definitely not where the regexp fails:

````bash
➜  test-tide rm -rf node_modules && npm install typescript@2.5
test-tide@1.0.0 /home/jostein/build/test-tide
└── typescript@2.5.3  extraneous

npm WARN test-tide@1.0.0 No description
npm WARN test-tide@1.0.0 No repository field.
➜  test-tide ./node_modules/.bin/tsc                          
test.ts(2,7): error TS2322: Type '2' is not assignable to type 'string'.
test.ts(2,7): error TS2451: Cannot redeclare block-scoped variable 'a'.
test.ts(2,28): error TS2322: Type '2' is not assignable to type 'string'.
test.ts(2,28): error TS2451: Cannot redeclare block-scoped variable 'a'.
➜  test-tide rm -rf node_modules && npm install typescript    
test-tide@1.0.0 /home/jostein/build/test-tide
└── typescript@2.9.2  extraneous

npm WARN test-tide@1.0.0 No description
npm WARN test-tide@1.0.0 No repository field.
➜  test-tide ./node_modules/.bin/tsc                      
test.ts:2:7 - error TS2322: Type '2' is not assignable to type 'string'.

2 const a: string = 2; const a: string = 2;
        ~


test.ts:2:7 - error TS2451: Cannot redeclare block-scoped variable 'a'.

2 const a: string = 2; const a: string = 2;
        ~


test.ts:2:28 - error TS2322: Type '2' is not assignable to type 'string'.

2 const a: string = 2; const a: string = 2;
                             ~


test.ts:2:28 - error TS2451: Cannot redeclare block-scoped variable 'a'.

2 const a: string = 2; const a: string = 2;
                             ~
````

It now also contains a marker `~` to show the column, for those who are to lazy to count :smile: 

Anyway, those who pay attention can see that there's a new file+line format "header":

* Old: `test.ts(2,28): `
* New: `test.ts:2:28 - `

I guess it should be doable to expand the regexp to also catch this kind of syntax... Or maybe it will be less messy to just create another regexp and leave both in place?

**Comment by KevinVillela** [comment]
Would it make sense to use a different regexp depending on the TypeScript version number? I think we should be able to figure out exactly when the error format was changed.

Or, just add both - that seems harmless enough :)

**Comment by josteink** [comment]
When it comes to `compilation-mode` my experience is that complex regexes are much more troublesome than multiple regexes.

Given how compilation-mode already have 100s of regexes I'll rather add a another one than needlessly complicating the one we have now.

I've added some stuff which may solve this issue, at least if ANSI colour-output isn't causing any problems for compilation-mode.

Let me know if it works for you.

**Comment by KevinVillela** [comment]
Woohoo thanks for the quick fix, that worked like a charm! Cheers!

**Comment by josteink** [comment]
New typescript release out and it mentions error-messages. 

Anyone wants to see if we need to add new regexps?

https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/

**Comment by lddubeau** [comment]
@josteink I've done a few tests with 3.0 but I've not run into a case where the regexp needed to be edited again. But that ain't saying much.

However, I notice the regexp that was recently added is named `typescript-tsc27-error-regexp`, which implies something to do with TypeScript version 2.7. I'm confused. The change was really introduced in TS 2.9. Moreover, the change was that from 2.9 onwards, `tsc` pretty prints the errors whereas ealier versions did not:

* `tsc` with 2.9 and later is equivalent to `tsc --pretty` with earlier versions.
* `tsc --pretty false` with 2.9 and later is equivalent to `tsc` with earlier versions.

Maybe `typescript-tsc-pretty-error-regexp` would be a better name (and perhaps a comment providing some historical context). Or did I completely miss what's going on here?

**Comment by josteink** [comment]
> However, I notice the regexp that was recently added is named typescript-tsc27-error-regexp, which implies something to do with TypeScript version 2.7. I'm confused. The change was really introduced in TS 2.9.

That's probably an error on my part not verifying in depth, but instead relying exclusively on the info provided by @KevinVillela. Sorry about being sloppy 😢 

So yes, feel free to correct this any way you feel more appropriate.

As for the naming, I thought basing it on a version made sense, since it may also change in other upcoming versions. If you're positive this is not actually related to versions though... Yes then I do agree about your judgement.

**Comment by KevinVillela** [comment]
Thanks for looking into this, I did some digging and found https://github.com/Microsoft/TypeScript/pull/20736, which is the PR that changed the error output format. It does seem like this is only the case for --pretty mode, although only in TS 2.7+. AFAICT, the change wasn't introduced in 2.9, it just became more prevalent when --pretty became the default. So, I'm fine with a name change and maybe a comment that includes the link to the PR.

**Comment by lddubeau** [comment]
@KevinVillela I did not know that. Thanks for the information. So the format change was introduced in 2.7 but did not become the default until 2.9. Still, I'm more concerned as to what the name implies to someone looking at the code without the historical background: the reason we have two regular expressions for `tsc` errors is that without `pretty`, one format is used, and with `pretty` a different format is used. This is true in 2.7, 2.8, 2.9, 3.0 and for the foreseeable future. When and how this came about is really secondary and becomes less and less likely to be an issue as time goes by.

**Comment by josteink** [comment]
So `typescript-tsc-pretty-error-regexp` it is then?
