### ISSUE TITLE
Over-indentation after call to `catch` method

### ISSUE THREAD

**Issue by Ptival** [ananthakumaran/typescript.el#85]
```
function f1(x) {
    return (
        x.then()
    )
}

function f2(x) {
    return (
        x.catch()
            )

```

(Sorry for all the issues! :-p)

**Comment by lddubeau** [comment]
If there's a bug, then an issue is appropriate. This problem does not happen only with `catch` though. I've been able to reproduce it with `finally` and `if` and there may be other keywords that trigger it.

A PR is welcome, though if you want to tackle it, I'd suggest finishing #82 first.
